CREATE TABLE users (
  id int unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  password VARCHAR( 64 ) NOT NULL,
  name VARCHAR( 64 ) NOT NULL,
  email VARCHAR( 32 ) NOT NULL,
  address VARCHAR( 32 ) DEFAULT '',
  phone VARCHAR( 64 ) DEFAULT ''
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE subjects (
  title VARCHAR( 32 ) PRIMARY KEY
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

CREATE TABLE complains (
  id INT unsigned NOT NULL AUTO_INCREMENT PRIMARY KEY,
  uid int( 32 ) DEFAULT NULL,
  title VARCHAR( 32 ) DEFAULT NULL,
  subject VARCHAR( 32 ),
  body TEXT NOT NULL,
  created DATETIME NOT NULL DEFAULT '0000-00-00-00-00',
  FOREIGN KEY (uid) REFERENCES users(id),
  FOREIGN KEY (subject) REFERENCES subjects(title)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;
